export * from './student-actions';
export const Action = {
    ERROR: "ERROR",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SIGNUP: "SIGNUP",
    PROFILE: "PROFILE",
    DISSMISS: "DISSMISS",
    GET_ALL_CLASS: "GET_ALL_CLASS",
    GET_CLASS_BY_DEPARTMENT: "GET_CLASS_BY_DEPARTMENT",
    GET_CLASS_BY_ID: "GET_CLASS_BY_ID",
    GET_CLASS_DETAILS_BY_CLASS_ID: "GET_CLASS_DETAILS_BY_CLASS_ID",
    GET_CLASS_DETAILS_BY_STUDENT_ID: "GET_CLASS_DETAILS_BY_STUDENT_ID",
    CREATE_CLASS_DETAILS: "CREATE_CLASS_DETAILS",
    CREATE_CLASS: "CREATE_CLASS",

}